/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    ACol: typeof import('ant-design-vue/es')['Col']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    DetailCol: typeof import('./src/components/DetailCol.vue')['default']
    HelpModal: typeof import('./src/components/HelpModal.vue')['default']
    IconR: typeof import('./src/components/icons/IconR.vue')['default']
    IntroModal: typeof import('./src/components/IntroModal.vue')['default']
    SchoolCard: typeof import('./src/components/SchoolCard.vue')['default']
    SchoolMap: typeof import('./src/components/SchoolMap.vue')['default']
    SchoolModal: typeof import('./src/components/SchoolModal.vue')['default']
    UserParamItem: typeof import('./src/components/UserParamItem.vue')['default']
  }
}
